export interface WResponse{
        rollId: string,
        date:string|Date;
        //winder 1
        w1TensionP1:number,
        w1TensionP2:number,
        w1TensionP3:number,
        w1TensionP4:number,
        w1TensionP5:number,
        w1TensionP6:number,
        w1TensionP7:number,
        w1TensionP8:number,
        w1TensionP9:number,
        w1TensionP10:number,
        w1TensionP11:number,
        w1TensionP12:number,
        w1TensionP13:number,
        w1TensionP14:number,
        w1TensionP15:number,
        w1TensionP16:number,
        w1TensionP17:number,
        w1TensionP18:number,
        w1TensionP19:number,
        w1TensionP20:number,
        //winder 2
        w2TensionP1:number,
        w2TensionP2:number,
        w2TensionP3:number,
        w2TensionP4:number,
        w2TensionP5:number,
        w2TensionP6:number,
        w2TensionP7:number,
        w2TensionP8:number,
        w2TensionP9:number,
        w2TensionP10:number,
        w2TensionP11:number,
        w2TensionP12:number,
        w2TensionP13:number,
        w2TensionP14:number,
        w2TensionP15:number,
        w2TensionP16:number,
        w2TensionP17:number,
        w2TensionP18:number,
        w2TensionP19:number,
        w2TensionP20:number,
}
