export interface WResponse{
        rollId: string,
        //winder 1
        w1TensionP1:string,
        w1TensionP2:string,
        w1TensionP3:string,
        w1TensionP4:string,
        w1TensionP5:string,
        w1TensionP6:string,
        w1TensionP7:string,
        w1TensionP8:string,
        w1TensionP9:string,
        w1TensionP10:string,
        w1TensionP11:string,
        w1TensionP12:string,
        w1TensionP13:string,
        w1TensionP14:string,
        w1TensionP15:string,
        w1TensionP16:string,
        w1TensionP17:string,
        w1TensionP18:string,
        w1TensionP19:string,
        w1TensionP20:string,
        //winder 2
        w2TensionP1:string,
        w2TensionP2:string,
        w2TensionP3:string,
        w2TensionP4:string,
        w2TensionP5:string,
        w2TensionP6:string,
        w2TensionP7:string,
        w2TensionP8:string,
        w2TensionP9:string,
        w2TensionP10:string,
        w2TensionP11:string,
        w2TensionP12:string,
        w2TensionP13:string,
        w2TensionP14:string,
        w2TensionP15:string,
        w2TensionP16:string,
        w2TensionP17:string,
        w2TensionP18:string,
        w2TensionP19:string,
        w2TensionP20:string,
}